version: "3"

includes:
  tests:
    taskfile: ./Requests.yml
    flatten: true

tasks:
  run-backend-dev:
    cmds:
      - cd src/backend && python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt && uvicorn main:app --reload --port 8000
    desc: Run the backend container for testing

  run-frontend-dev:
    cmds:
      - cd src/frontend && npm install && npm run start
    desc: Run the frontend container for testing


  decrypt-and-login:
    cmds:
      - gpg --output credentials.json --decrypt student-service-account-credentials.json.gpg
      - gcloud auth activate-service-account --key-file=credentials.json
      - rm credentials.json
      - gcloud auth configure-docker europe-west4-docker.pkg.dev --quiet
      - gcloud config set project recr-praxistag-url-shortener --quiet
      - gcloud config set run/region europe-west4 --quiet
    desc: Decrypt the service account credentials and login to Google
