version: "3"

includes:
  tests:
    taskfile: ./Requests.yml
    flatten: true

tasks:
  build-backend:
    cmds:
      - docker build -t url-shortener-backend -f ./src/backend/Dockerfile .
    desc: Build the backend Docker image

  build-frontend:
    cmds:
      - docker build -t url-shortener-frontend -f src/frontend/Dockerfile .
    desc: Build the frontend Docker image

  run-backend:
    cmds:
      - docker run -d -p 8000:8000 --name backend url-shortener-backend
    desc: Run the backend container

  run-backend-dev:
    cmds:
      - cd src/backend && python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt && uvicorn main:app --reload --host 0.0.0.0 --port 8000
    desc: Run the backend container for testing

  run-frontend:
    cmds:
      - docker run -d -p 80:80 --name frontend url-shortener-frontend
    desc: Run the frontend container

  run-frontend-dev:
    cmds:
      - cd src/frontend && npm run ng serve
    desc: Run the frontend container for testing

  run-dev:
    deps:
      [stop, build-backend, build-frontend, run-backend-dev, run-frontend-dev]
    desc: Build and run both backend and frontend

  run:
    deps: [stop, build-backend, build-frontend, run-backend, run-frontend]
    desc: Build and run both backend and frontend

  stop:
    cmds:
      - docker stop $(docker ps -q) || true
    desc: Stop running containers gracefully

  kill:
    cmds:
      - docker kill $(docker ps -q) || true
    desc: Kill running containers

  stats:
    cmds:
      - docker stats
    desc: Show container stats
