version: "3"

includes:
  tests:
    taskfile: ./Requests.yml
    flatten: true

tasks:
  run:
    deps:
      - stop
      - build
    cmds:
      - docker run -d -p 8080:8080 -p 8000:8000 --name url-shortener url-shortener     
    desc: Stop, build and run the url shortener container

  build:
    cmds:
      - docker build -t url-shortener .
    desc: Build the applications Docker image

  run-backend-dev:
    cmds:
      - cd src/backend && python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt && uvicorn main:app --reload --port 8000
    desc: Run the backend container for testing

  run-frontend-dev:
    cmds:
      - cd src/frontend && npm install && npm run start
    desc: Run the frontend container for testing

  run-dev:
    desc: Run frontend and backend together; stop both on Ctrl+C
    deps:
      - run-backend-dev
      - run-frontend-dev

  open-task:
    desc: Open the Jira-style task page in your default browser
    cmds:
      - >
        (command -v open >/dev/null 2>&1 && open jira_task.html)
        || (command -v xdg-open >/dev/null 2>&1 && xdg-open jira_task.html)
        || (command -v powershell.exe >/dev/null 2>&1 && powershell.exe -NoProfile -Command Start-Process "$(pwd)/jira_task.html")
        || echo "Please open ./jira_task.html manually in your browser."
